import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {useEffect, useState} from 'react'


export default function Home() {
	const [progress, setProgress] = useState(0);
	const [url, setUrl] = useState(undefined);

	async function getAPIUrl() {
		const word = url.split('/');
		const sheetId = word[5];
		const apiString = `https://sheets.googleapis.com/v4/spreadsheets/${sheetId}/values/L0!F1:F132?majorDimension=COLUMNS&key=AIzaSyCV2eNlUyRZzWbpCByF9f4sksTME9m__wo`;
	
		let res = await fetch(apiString)
			
		return res.json();
	}
	function getCompletedPercentage(colValues) {
		let count = 0;
		for(let i = 1; i < colValues.length; i++) {
          if(colValues[i] === "Completed") {
			  count++;
		  }
		}
		return (count/colValues.length)*100;

	}
	function handleUrlInput(e) {
		setUrl(e.target.value);
	}
	useEffect(() => {
		if (!url) return;
		getAPIUrl()
			.then((res) => {
				const colValues = res["values"][0];
				setProgress(getCompletedPercentage(colValues))

			})
	}, [url])

		return (
			<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={{display: 'flex'}}>
				<h1 className={styles.title}>
				<a href="/">B-Talent </a>
				</h1>
				
			    <a href="/">Enter your excel sheet </a>
				<input onChange={handleUrlInput} />
				{`Your progress is ${progress}`}
				 `Your Url is ${url}'
			

				<div className={styles.grid}>
				<a href="https://online.actitime.com/bidgely/timetrack/enter.do" className={styles.card}>
					<h2>ActiTime &rarr;</h2>
					<p>(TimeSheet)</p>
				</a>

				<a href="https://bidgely.greythr.com/" className={styles.card}>
					<h2>greytHR &rarr;</h2>
					<p>(Leave, Payroll & Expense)</p>
				</a>

				<a
					href="https://sites.google.com/bidgely.com/b-wiki/home/engineering/library/products"
					className={styles.card}
				>
					<h2>B-Wiki &rarr;</h2>
					<p>(Bidgely Wikipedia)</p>
				</a>

				<a
					href="https://insighttimer.com/en-in"
					className={styles.card}
				>
					<h2>Insight Timer &rarr;</h2>
					<p>(Mental Wellbeing)</p>
				</a>


				<a
					href="https://docs.google.com/spreadsheets/d/1oBfsODjR5rHbjUsucXGma5Lnrur-TURB/edit#gid=2000694853"
					className={styles.card}
				>
					<h2>Lombard &rarr;</h2>
					<p>
					(Medical Insurance)
					</p>
				</a>
				</div>
			</main>

			{/* <footer className={styles.footer}>
				<a
				href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
				target="_blank"
				rel="noopener noreferrer"
				>
				Powered by{' '}
				<span className={styles.logo}>
					<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
				</span>
				</a>
			</footer> */}
			</div>
	)
}
